#!/usr/bin/env python3
"""Generate a skill catalog from all skill.md files in the skills/ directory."""

from __future__ import annotations

from pathlib import Path

from libs.skills.loader import load_all_skills

SKILLS_ROOT = Path("skills")
CATALOG_DIR = Path("docs/skills")


def main() -> None:
    CATALOG_DIR.mkdir(parents=True, exist_ok=True)

    skills = load_all_skills([SKILLS_ROOT])
    skills.sort(key=lambda s: (s.phase, s.skill_key))

    # Generate catalog index
    lines = [
        "# Skill Catalog",
        "",
        f"**Total skills:** {len(skills)}",
        "",
        "| ID | Phase | Version | Risk | Valid | Description |",
        "|----|-------|---------|------|-------|-------------|",
    ]

    for skill in skills:
        desc = skill.body_markdown.split("\n")[0].strip("# ").strip() if skill.body_markdown else ""
        valid = "Yes" if skill.is_valid else "No"
        lines.append(
            f"| [{skill.skill_key}](skills/{skill.skill_key}.md) "
            f"| {skill.phase} "
            f"| {skill.version} "
            f"| {skill.manifest.risk_level} "
            f"| {valid} "
            f"| {desc} |"
        )

    lines.extend(["", "---", "", "*Generated by `scripts/generate_skill_catalog.py`*", ""])
    (CATALOG_DIR / "catalog.md").write_text("\n".join(lines), encoding="utf-8")

    # Generate per-skill detail pages
    for skill in skills:
        detail_lines = [
            f"# {skill.skill_key}",
            "",
            "## Manifest",
            "",
            f"- **ID:** {skill.manifest.id}",
            f"- **Version:** {skill.version}",
            f"- **Phase:** {skill.phase}",
            f"- **Risk Level:** {skill.manifest.risk_level}",
            f"- **Allowed Operators:** {', '.join(skill.manifest.allowed_operators)}",
            f"- **Outputs:** {', '.join(skill.manifest.outputs)}",
            f"- **Capabilities:** {', '.join(skill.manifest.capabilities)}",
            f"- **Valid:** {'Yes' if skill.is_valid else 'No'}",
        ]
        if skill.manifest.requires:
            detail_lines.append(f"- **Requires:** {', '.join(skill.manifest.requires)}")
        if skill.manifest.conflicts_with:
            detail_lines.append(f"- **Conflicts With:** {', '.join(skill.manifest.conflicts_with)}")
        if skill.hook_exports:
            detail_lines.append(f"- **Hook Exports:** {', '.join(skill.hook_exports)}")
        if skill.validation_issues:
            detail_lines.extend(["", "## Validation Issues", ""])
            for issue in skill.validation_issues:
                sev = issue.get("severity", "?")
                msg = issue.get("message", "?")
                detail_lines.append(f"- **{sev}:** {msg}")

        detail_lines.extend(["", "## Documentation", "", skill.body_markdown, ""])
        (CATALOG_DIR / f"{skill.skill_key}.md").write_text(
            "\n".join(detail_lines), encoding="utf-8"
        )

    print(f"Generated catalog with {len(skills)} skills in {CATALOG_DIR}/")


if __name__ == "__main__":
    main()
